apiVersion: v1
data:
  name: dGVzdDI=
  project: dGlja2V0aW5n
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFyQUFBQUJObFkyUnpZUwoxemFHRXlMVzVwYzNSd05USXhBQUFBQ0c1cGMzUndOVEl4QUFBQWhRUUFxR241M3JGRU1LWHN1SG9UMzJxV3BRaUNQd1ZuCjdKL3prS2pwWE5RNStoZVBDejZFNjM4akJ6Ukc2YXBCWkZVQTF3dlBFbmErVUN4OHkxbUh0SzZ0cGkwQlAyVThoTkoyZGMKb1JGWWlHb25rdkNEcWI2VWYrZnh5bm0rU3FvM2RHTnM4Tnl5Q21QL3BINGpwYXQycmFMbXltTERaZzZsditqV3c1Yi9oMgpxdlpMdnl3QUFBRVlITnFneEJ6YW9NUUFBQUFUWldOa2MyRXRjMmhoTWkxdWFYTjBjRFV5TVFBQUFBaHVhWE4wY0RVeU1RCkFBQUlVRUFLaHArZDZ4UkRDbDdMaDZFOTlxbHFVSWdqOEZaK3lmODVDbzZWelVPZm9YandzK2hPdC9Jd2MwUnVtcVFXUlYKQU5jTHp4SjJ2bEFzZk10Wmg3U3VyYVl0QVQ5bFBJVFNkblhLRVJXSWhxSjVMd2c2bStsSC9uOGNwNXZrcXFOM1JqYlBEYwpzZ3BqLzZSK0k2V3JkcTJpNXNwaXcyWU9wYi9vMXNPVy80ZHFyMlM3OHNBQUFBUWdHQ1ROTWNXeWgrajNlSExGeVlvM3QxCklCZGEvanNSaGhNNlVTTmlmbjFCVm5mU0tudXpkazhJc2N5UGNOZ2NqV3dJRlE5WWJJeUZFUFo4aFFjaWVHOFltd0FBQUIKWjViM1Z5WDJWdFlXbHNRR1Y0WVcxd2JHVXVZMjl0QVFJREJBPT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0t
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206emVhYml4LUVudGVydGFpbm1lbnQvei1EZXZTZWNPcHMuZ2l0
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-1579438019
  namespace: argocd
type: Opaque
