# kaitest11
name: dast-master

on:
  workflow_call:
  
#   inputs:
#     workflow_name:
#       required: true
#       type: string

#   secrets:
#     github_token:
#     required: true
#     sonar_token:
#       required: true

#env:
#  WORKFLOW_NAME: ${{inputs.workflow_name}}
    
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: owasp-zap
    steps:
      - name: execute
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'https://www.z-commerce-dev.zeabix.com/'



 