# kaitest11345
name: dast-master

on:
  workflow_call:
  
#   inputs:
#     workflow_name:
#       required: true
#       type: string

#   secrets:
#     github_token:
#     required: true
#     sonar_token:
#       required: true

#env:
#  WORKFLOW_NAME: ${{inputs.workflow_name}}
    
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: owasp-zap
    steps:
      - name: execute
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'https://z-commerce-dev.zeabix.com/'
  
  burp-suite:
    runs-on: ubuntu-latest
    name: burp-suite
    steps:
      - name: Install  burp-ci-driver
        run: wget https://zeabixblob1.blob.core.windows.net/blob-container/burp-ci-driver-2021.3-162.jar
      
      - name: execute
        run: |
          java -jar ./burp-ci-driver-2021.3-162.jar $BURP_URL \
          --api-key=$API_KEY --site-id=$SITE_ID --min-severity=$MIN_SERV \
          --min-confidence=$MIN_CON --report-file=$REPORT_FILE_NAME --report-type=$REPORT_TYPE
        env:
          BURP_URL: "http://20.24.144.124:8080"
          API_KEY:  "m7mRSY1MVo4MOaSCeV4LRwmPcUuHC1yB"
          SITE_ID: "1"
          MIN_SERV: "high"
          MIN_CON: "certain"
          REPORT_TYPE: "detailed"
          REPORT_FILE_NAME: "burp-report.html"
        
      - name: Upload report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: burp-report
          path: burp-report.html
      




# https://www.lunavi.com/blog/using-the-owasp-zap-baseline-scan-github-action

# How to schedule owasp-zap
# https://www.zaproxy.org/blog/2020-04-09-automate-security-testing-with-zap-and-github-actions/

# Detail of built-in-configuration
# https://portswigger.net/burp/documentation/desktop/scanning/built-in-configurations

# How to enable embedded browser (powered browser) for Burp Suite
# You need to install chrome for Ubuntu first
#     https://www.linuxcapable.com/how-to-install-google-chrome-on-ubuntu-20-04/
#
# https://portswigger.net/burp/documentation/enterprise/reference/browser-powered


# Burp Suite VM Specification
#
# Base with 1scaner (single machine installation): 8vCPU, 24GB. 30GB Disk
# https://portswigger.net/burp/documentation/enterprise/getting-started/system-requirements
 