# kaitest11
name: dast-master

on:
  workflow_call:
  
#   inputs:
#     workflow_name:
#       required: true
#       type: string

    secrets:
#     github_token:
#     required: true
      sonar_token:
        required: true

#env:
#  WORKFLOW_NAME: ${{inputs.workflow_name}}
    
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.3.0
      with:
       target: 'https://z-commerce-dev.zeabix.com/'

 