# kaitest11
name: dast-master

on:
  workflow_call:
  
#   inputs:
#     workflow_name:
#       required: true
#       type: string

#   secrets:
#     github_token:
#     required: true
#     sonar_token:
#       required: true

#env:
#  WORKFLOW_NAME: ${{inputs.workflow_name}}
    
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: owasp-zap
    steps:
      - name: execute
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'https://z-commerce-dev.zeabix.com/'

# https://www.lunavi.com/blog/using-the-owasp-zap-baseline-scan-github-action

# How to schedule owasp-zap
# https://www.zaproxy.org/blog/2020-04-09-automate-security-testing-with-zap-and-github-actions/
 