# kaitest123456
name: DEV_ticketing-client_client

on:
  push:
    branches:
      - feature-*
jobs:
  sast:
    uses: ./.github/workflows/sast-master.yaml
#   with: 
#     workflow_name: ${{github.workflow}}
    secrets:
#     github_token: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  build:
    uses: ./.github/workflows/build-master.yaml
#   with: 
#     workflow_name: ${{github.workflow}}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-master.yaml
    with:
      workflow_name: ${{github.workflow}}
      docker_tag: ${{needs.build.outputs.docker_tag}}
  
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      creds:  '${{ secrets.AZURE_CREDENTIALS_DEV }}'
      cluster-name: ${{ secrets.CLUSTER_NAME_DEV }}
      resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP_DEV }}